### PR TITLE
Library version upgrade

### PR DESCRIPTION
**Pull request by mondoktamas**

### CODE REVIEW

**Review by Fasust — CHANGES_REQUESTED** [review]
Getting this version conflict when using it in fastic:

````
 Because fasting depends on device_preview from git which depends on freezed_annotation ^0.12.0, freezed_annotation ^0.12.0 is required.
So, because fasting depends on freezed_annotation ^0.11.0, version solving failed.
Running "flutter pub get" in fasting-app...                             
pub get failed (1; So, because fasting depends on freezed_annotation ^0.11.0, version solving failed.)
````

**Comment by mondoktamas** [comment]
@Fasust this PR will be needed for the library upgrade task, on that branch i already upgraded the related libs

**Comment by Fasust** [comment]
@mondoktamas Okay, we should only merge it when you merged the version migration into fastic then. For now you can just depend on the branch, right?

**Comment by mondoktamas** [comment]
@Fasust yes

**Pull request closed without merging**
